{% set name = "comet-ml" %}
{% set version = "3.49.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/comet_ml-{{ version }}.tar.gz
  sha256: fd4e2b71bf0d2a95e1cd2c0bdfbd6c57a3b02db273f60a4ab4590a00df09f5d8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - comet = comet_ml.scripts.comet:main
    - comet_ml.spacy.logger.v1 = comet_ml.integration.spacy:comet_logger_v1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - configobj
    - dulwich >=0.20.6,!=0.20.33
    - everett >=1.0.1,<3.2.0
    - importlib-metadata
    - jsonschema >=2.6.0,!=3.1.0
    - psutil >=5.6.3
    - python-box <7.0.0
    - requests-toolbelt >=0.8.0
    - requests >=2.18.4
    - rich >=13.3.2
    - semantic_version >=2.8.0
    - sentry-sdk >=1.1.0
    - simplejson
    - urllib3 >=1.21.1
    - wrapt >=1.11.2
    - wurlitzer >=1.0.2

test:
  imports:
    - comet_ml
  commands:
    - pip check
    - comet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.comet.com
  summary: Supercharging Machine Learning
  license: MIT
  license_file: README.rst

extra:
  recipe-maintainers:
    - jeongseok-meta
